// This file is auto-generated by @hey-api/openapi-ts

import type { FetchesRequestParams, ApicraftFetchesResponse } from '@siberiacancode/apicraft';

import type {
  GetAnimeByGenreGenresSlugAnimeGetData,
  GetAnimeByGenreGenresSlugAnimeGetResponse,
  GetAnimeByGenreGenresSlugAnimeGetError
} from '..//..//types.gen';

import { instance } from '../../instance.gen';

export type GetGenreBySlugAnimeRequestParams =
  FetchesRequestParams<GetAnimeByGenreGenresSlugAnimeGetData>;

export const getGenreBySlugAnime = ({
  config,
  query,
  path
}: GetGenreBySlugAnimeRequestParams): Promise<
  ApicraftFetchesResponse<
    GetAnimeByGenreGenresSlugAnimeGetResponse,
    GetAnimeByGenreGenresSlugAnimeGetError
  >
> =>
  instance.call('GET', `/genres/${path.slug}/anime`, {
    query,
    ...config
  });
