// This file is auto-generated by @hey-api/openapi-ts

import type { FetchesRequestParams, ApicraftFetchesResponse } from '@siberiacancode/apicraft';

import type { GetGenresGenresGetData, GetGenresGenresGetResponse } from '..//..//types.gen';

import { instance } from '../../instance.gen';

export type GetGenresRequestParams = FetchesRequestParams<GetGenresGenresGetData> | void;

export const getGenres = ({ config }: GetGenresRequestParams = {}): Promise<
  ApicraftFetchesResponse<GetGenresGenresGetResponse>
> =>
  instance.call('GET', '/genres', {
    ...config
  });
