// This file is auto-generated by @hey-api/openapi-ts

import type { FetchesRequestParams, ApicraftFetchesResponse } from '@siberiacancode/apicraft';

import type {
  SearchAnimeShortSearchGetData,
  SearchAnimeShortSearchGetResponse,
  SearchAnimeShortSearchGetError
} from '..//..//types.gen';

import { instance } from '../../instance.gen';

export type GetShortSearchRequestParams = FetchesRequestParams<SearchAnimeShortSearchGetData>;

export const getShortSearch = ({
  config,
  query
}: GetShortSearchRequestParams): Promise<
  ApicraftFetchesResponse<SearchAnimeShortSearchGetResponse, SearchAnimeShortSearchGetError>
> =>
  instance.call('GET', '/short-search/', {
    query,
    ...config
  });
