// This file is auto-generated by @hey-api/openapi-ts

import type { FetchesRequestParams, ApicraftFetchesResponse } from '@siberiacancode/apicraft';

import type {
  GetTranslationTranslationGetData,
  GetTranslationTranslationGetResponse,
  GetTranslationTranslationGetError
} from '..//..//types.gen';

import { instance } from '../../instance.gen';

export type GetTranslationRequestParams = FetchesRequestParams<GetTranslationTranslationGetData>;

export const getTranslation = ({
  config,
  query
}: GetTranslationRequestParams): Promise<
  ApicraftFetchesResponse<GetTranslationTranslationGetResponse, GetTranslationTranslationGetError>
> =>
  instance.call('GET', '/translation', {
    query,
    ...config
  });
