// This file is auto-generated by @hey-api/openapi-ts

import type { FetchesRequestParams, ApicraftFetchesResponse } from '@siberiacancode/apicraft';

import type { RootGetData } from '..//..//types.gen';

import { instance } from '../../instance.gen';

export type GetRequestParams = FetchesRequestParams<RootGetData> | void;

export const get = ({ config }: GetRequestParams = {}): Promise<ApicraftFetchesResponse> =>
  instance.call('GET', '/', {
    ...config
  });
