// This file is auto-generated by @hey-api/openapi-ts

import type { FetchesRequestParams, ApicraftFetchesResponse } from '@siberiacancode/apicraft';

import type { GetPopularsPopularsGetData, GetPopularsPopularsGetResponse } from '..//..//types.gen';

import { instance } from '../../instance.gen';

export type GetPopularsRequestParams = FetchesRequestParams<GetPopularsPopularsGetData> | void;

export const getPopulars = ({ config }: GetPopularsRequestParams = {}): Promise<
  ApicraftFetchesResponse<GetPopularsPopularsGetResponse>
> =>
  instance.call('GET', '/populars', {
    ...config
  });
