// This file is auto-generated by @hey-api/openapi-ts

import type { UseQueryOptions } from "@tanstack/react-query";

import { queryOptions, useQuery } from "@tanstack/react-query";

import type { MeAuthMeGetError } from "..//..//types.gen";

import { getAuthMe } from "..//..//requests//auth//getAuthMe.gen";

type GetAuthMeHookData = Awaited<ReturnType<typeof getAuthMe>>;

export const getAuthMeQueryKey = "getAuthMeQueryKey";

export const getAuthMeQueryOptions = <TData = GetAuthMeHookData, TError = MeAuthMeGetError>(settings?: {
    params?: Omit<UseQueryOptions<GetAuthMeHookData, TError, TData>, "queryKey">;
    request?: NonNullable<Parameters<typeof getAuthMe>[0]>;
}) => queryOptions({
    queryKey: [getAuthMeQueryKey, ...(!!settings?.request?.path ? [settings?.request?.path] : []), ...(!!settings?.request?.query ? [settings?.request?.query] : []), ...(!!settings?.request?.body ? [settings?.request?.body] : [])],
    queryFn: async () => getAuthMe({ ...settings?.request }),
    ...settings?.params
});

export const useGetAuthMeQuery = <TData = GetAuthMeHookData, TError = MeAuthMeGetError>(...args: Parameters<typeof getAuthMeQueryOptions<TData, TError>>) => useQuery(getAuthMeQueryOptions<TData, TError>(...args));