// This file is auto-generated by @hey-api/openapi-ts

import type { UseSuspenseQueryOptions } from "@tanstack/react-query";

import { queryOptions, useSuspenseQuery } from "@tanstack/react-query";

import type { MeAuthMeGetError } from "..//..//types.gen";

import { getAuthMe } from "..//..//requests//auth//getAuthMe.gen";

type GetAuthMeHookData = Awaited<ReturnType<typeof getAuthMe>>;

export const getAuthMeSuspenseQueryKey = "getAuthMeSuspenseQueryKey";

export const getAuthMeSuspenseQueryOptions = <TData = GetAuthMeHookData, TError = MeAuthMeGetError>(settings?: {
    params?: Omit<UseSuspenseQueryOptions<GetAuthMeHookData, TError, TData>, "queryKey">;
    request?: NonNullable<Parameters<typeof getAuthMe>[0]>;
}) => queryOptions({
    queryKey: [getAuthMeSuspenseQueryKey, ...(!!settings?.request?.path ? [settings?.request?.path] : []), ...(!!settings?.request?.query ? [settings?.request?.query] : []), ...(!!settings?.request?.body ? [settings?.request?.body] : [])],
    queryFn: async () => getAuthMe({ ...settings?.request }),
    ...settings?.params
});

export const useGetAuthMeSuspenseQuery = <TData = GetAuthMeHookData, TError = MeAuthMeGetError>(...args: Parameters<typeof getAuthMeSuspenseQueryOptions<TData, TError>>) => useSuspenseQuery(getAuthMeSuspenseQueryOptions<TData, TError>(...args));