// This file is auto-generated by @hey-api/openapi-ts

import type { UseMutationOptions } from "@tanstack/react-query";

import { useMutation } from "@tanstack/react-query";

import type { MeAuthMeGetError } from "..//..//types.gen";

import { getAuthMe } from "..//..//requests//auth//getAuthMe.gen";

type GetAuthMeHookData = Awaited<ReturnType<typeof getAuthMe>>;

export const getAuthMeMutationKey = "getAuthMeMutationKey";

type GetAuthMeMutationVariables = Parameters<typeof getAuthMe>[0];

export const useGetAuthMeMutation = <TError = MeAuthMeGetError, TContext = unknown>(settings?: {
    params?: UseMutationOptions<GetAuthMeHookData, TError, GetAuthMeMutationVariables, TContext>;
    request?: NonNullable<GetAuthMeMutationVariables>;
}) => useMutation({
    mutationKey: [getAuthMeMutationKey],
    mutationFn: async (params) => getAuthMe({ ...settings?.request, ...params }),
    ...settings?.params
});