// This file is auto-generated by @hey-api/openapi-ts

import type { UseSuspenseQueryOptions } from "@tanstack/react-query";

import { queryOptions, useSuspenseQuery } from "@tanstack/react-query";

import type { LogoutAuthLogoutPostError } from "..//..//types.gen";

import { postAuthLogout } from "..//..//requests//auth//postAuthLogout.gen";

type PostAuthLogoutHookData = Awaited<ReturnType<typeof postAuthLogout>>;

export const postAuthLogoutSuspenseQueryKey = "postAuthLogoutSuspenseQueryKey";

export const postAuthLogoutSuspenseQueryOptions = <TData = PostAuthLogoutHookData, TError = LogoutAuthLogoutPostError>(settings?: {
    params?: Omit<UseSuspenseQueryOptions<PostAuthLogoutHookData, TError, TData>, "queryKey">;
    request?: NonNullable<Parameters<typeof postAuthLogout>[0]>;
}) => queryOptions({
    queryKey: [postAuthLogoutSuspenseQueryKey, ...(!!settings?.request?.path ? [settings?.request?.path] : []), ...(!!settings?.request?.query ? [settings?.request?.query] : []), ...(!!settings?.request?.body ? [settings?.request?.body] : [])],
    queryFn: async () => postAuthLogout({ ...settings?.request }),
    ...settings?.params
});

export const usePostAuthLogoutSuspenseQuery = <TData = PostAuthLogoutHookData, TError = LogoutAuthLogoutPostError>(...args: Parameters<typeof postAuthLogoutSuspenseQueryOptions<TData, TError>>) => useSuspenseQuery(postAuthLogoutSuspenseQueryOptions<TData, TError>(...args));