// This file is auto-generated by @hey-api/openapi-ts

import type { UseSuspenseQueryOptions } from "@tanstack/react-query";

import { queryOptions, useSuspenseQuery } from "@tanstack/react-query";

import type { LoginAuthLoginPostError } from "..//..//types.gen";

import { postAuthLogin } from "..//..//requests//auth//postAuthLogin.gen";

type PostAuthLoginHookData = Awaited<ReturnType<typeof postAuthLogin>>;

export const postAuthLoginSuspenseQueryKey = "postAuthLoginSuspenseQueryKey";

export const postAuthLoginSuspenseQueryOptions = <TData = PostAuthLoginHookData, TError = LoginAuthLoginPostError>(settings: {
    params?: Omit<UseSuspenseQueryOptions<PostAuthLoginHookData, TError, TData>, "queryKey">;
    request: NonNullable<Parameters<typeof postAuthLogin>[0]>;
}) => queryOptions({
    queryKey: [postAuthLoginSuspenseQueryKey, ...(!!settings.request.path ? [settings.request.path] : []), ...(!!settings.request.query ? [settings.request.query] : []), ...(!!settings.request.body ? [settings.request.body] : [])],
    queryFn: async () => postAuthLogin({ ...settings.request }),
    ...settings.params
});

export const usePostAuthLoginSuspenseQuery = <TData = PostAuthLoginHookData, TError = LoginAuthLoginPostError>(...args: Parameters<typeof postAuthLoginSuspenseQueryOptions<TData, TError>>) => useSuspenseQuery(postAuthLoginSuspenseQueryOptions<TData, TError>(...args));