// This file is auto-generated by @hey-api/openapi-ts

import type { UseSuspenseQueryOptions } from "@tanstack/react-query";

import { queryOptions, useSuspenseQuery } from "@tanstack/react-query";

import type { RegisterAuthRegisterPostError } from "..//..//types.gen";

import { postAuthRegister } from "..//..//requests//auth//postAuthRegister.gen";

type PostAuthRegisterHookData = Awaited<ReturnType<typeof postAuthRegister>>;

export const postAuthRegisterSuspenseQueryKey = "postAuthRegisterSuspenseQueryKey";

export const postAuthRegisterSuspenseQueryOptions = <TData = PostAuthRegisterHookData, TError = RegisterAuthRegisterPostError>(settings: {
    params?: Omit<UseSuspenseQueryOptions<PostAuthRegisterHookData, TError, TData>, "queryKey">;
    request: NonNullable<Parameters<typeof postAuthRegister>[0]>;
}) => queryOptions({
    queryKey: [postAuthRegisterSuspenseQueryKey, ...(!!settings.request.path ? [settings.request.path] : []), ...(!!settings.request.query ? [settings.request.query] : []), ...(!!settings.request.body ? [settings.request.body] : [])],
    queryFn: async () => postAuthRegister({ ...settings.request }),
    ...settings.params
});

export const usePostAuthRegisterSuspenseQuery = <TData = PostAuthRegisterHookData, TError = RegisterAuthRegisterPostError>(...args: Parameters<typeof postAuthRegisterSuspenseQueryOptions<TData, TError>>) => useSuspenseQuery(postAuthRegisterSuspenseQueryOptions<TData, TError>(...args));