// This file is auto-generated by @hey-api/openapi-ts

import type { UseQueryOptions } from "@tanstack/react-query";

import { queryOptions, useQuery } from "@tanstack/react-query";

import type { RegisterAuthRegisterPostError } from "..//..//types.gen";

import { postAuthRegister } from "..//..//requests//auth//postAuthRegister.gen";

type PostAuthRegisterHookData = Awaited<ReturnType<typeof postAuthRegister>>;

export const postAuthRegisterQueryKey = "postAuthRegisterQueryKey";

export const postAuthRegisterQueryOptions = <TData = PostAuthRegisterHookData, TError = RegisterAuthRegisterPostError>(settings: {
    params?: Omit<UseQueryOptions<PostAuthRegisterHookData, TError, TData>, "queryKey">;
    request: NonNullable<Parameters<typeof postAuthRegister>[0]>;
}) => queryOptions({
    queryKey: [postAuthRegisterQueryKey, ...(!!settings.request.path ? [settings.request.path] : []), ...(!!settings.request.query ? [settings.request.query] : []), ...(!!settings.request.body ? [settings.request.body] : [])],
    queryFn: async () => postAuthRegister({ ...settings.request }),
    ...settings.params
});

export const usePostAuthRegisterQuery = <TData = PostAuthRegisterHookData, TError = RegisterAuthRegisterPostError>(...args: Parameters<typeof postAuthRegisterQueryOptions<TData, TError>>) => useQuery(postAuthRegisterQueryOptions<TData, TError>(...args));