// This file is auto-generated by @hey-api/openapi-ts

import type { UseMutationOptions } from "@tanstack/react-query";

import { useMutation } from "@tanstack/react-query";

import type { RegisterAuthRegisterPostError } from "..//..//types.gen";

import { postAuthRegister } from "..//..//requests//auth//postAuthRegister.gen";

type PostAuthRegisterHookData = Awaited<ReturnType<typeof postAuthRegister>>;

export const postAuthRegisterMutationKey = "postAuthRegisterMutationKey";

type PostAuthRegisterMutationVariables = Parameters<typeof postAuthRegister>[0];

export const usePostAuthRegisterMutation = <TError = RegisterAuthRegisterPostError, TContext = unknown>(settings?: {
    params?: UseMutationOptions<PostAuthRegisterHookData, TError, PostAuthRegisterMutationVariables, TContext>;
    request?: NonNullable<PostAuthRegisterMutationVariables>;
}) => useMutation({
    mutationKey: [postAuthRegisterMutationKey],
    mutationFn: async (params) => postAuthRegister({ ...settings?.request, ...params }),
    ...settings?.params
});