// This file is auto-generated by @hey-api/openapi-ts

import type { UseQueryOptions } from "@tanstack/react-query";

import { queryOptions, useQuery } from "@tanstack/react-query";

import type { LogoutAuthLogoutPostError } from "..//..//types.gen";

import { postAuthLogout } from "..//..//requests//auth//postAuthLogout.gen";

type PostAuthLogoutHookData = Awaited<ReturnType<typeof postAuthLogout>>;

export const postAuthLogoutQueryKey = "postAuthLogoutQueryKey";

export const postAuthLogoutQueryOptions = <TData = PostAuthLogoutHookData, TError = LogoutAuthLogoutPostError>(settings?: {
    params?: Omit<UseQueryOptions<PostAuthLogoutHookData, TError, TData>, "queryKey">;
    request?: NonNullable<Parameters<typeof postAuthLogout>[0]>;
}) => queryOptions({
    queryKey: [postAuthLogoutQueryKey, ...(!!settings?.request?.path ? [settings?.request?.path] : []), ...(!!settings?.request?.query ? [settings?.request?.query] : []), ...(!!settings?.request?.body ? [settings?.request?.body] : [])],
    queryFn: async () => postAuthLogout({ ...settings?.request }),
    ...settings?.params
});

export const usePostAuthLogoutQuery = <TData = PostAuthLogoutHookData, TError = LogoutAuthLogoutPostError>(...args: Parameters<typeof postAuthLogoutQueryOptions<TData, TError>>) => useQuery(postAuthLogoutQueryOptions<TData, TError>(...args));