// This file is auto-generated by @hey-api/openapi-ts

import type { UseQueryOptions } from "@tanstack/react-query";

import { queryOptions, useQuery } from "@tanstack/react-query";

import type { LoginAuthLoginPostError } from "..//..//types.gen";

import { postAuthLogin } from "..//..//requests//auth//postAuthLogin.gen";

type PostAuthLoginHookData = Awaited<ReturnType<typeof postAuthLogin>>;

export const postAuthLoginQueryKey = "postAuthLoginQueryKey";

export const postAuthLoginQueryOptions = <TData = PostAuthLoginHookData, TError = LoginAuthLoginPostError>(settings: {
    params?: Omit<UseQueryOptions<PostAuthLoginHookData, TError, TData>, "queryKey">;
    request: NonNullable<Parameters<typeof postAuthLogin>[0]>;
}) => queryOptions({
    queryKey: [postAuthLoginQueryKey, ...(!!settings.request.path ? [settings.request.path] : []), ...(!!settings.request.query ? [settings.request.query] : []), ...(!!settings.request.body ? [settings.request.body] : [])],
    queryFn: async () => postAuthLogin({ ...settings.request }),
    ...settings.params
});

export const usePostAuthLoginQuery = <TData = PostAuthLoginHookData, TError = LoginAuthLoginPostError>(...args: Parameters<typeof postAuthLoginQueryOptions<TData, TError>>) => useQuery(postAuthLoginQueryOptions<TData, TError>(...args));