// This file is auto-generated by @hey-api/openapi-ts

import type { UseMutationOptions } from "@tanstack/react-query";

import { useMutation } from "@tanstack/react-query";

import type { LogoutAuthLogoutPostError } from "..//..//types.gen";

import { postAuthLogout } from "..//..//requests//auth//postAuthLogout.gen";

type PostAuthLogoutHookData = Awaited<ReturnType<typeof postAuthLogout>>;

export const postAuthLogoutMutationKey = "postAuthLogoutMutationKey";

type PostAuthLogoutMutationVariables = Parameters<typeof postAuthLogout>[0];

export const usePostAuthLogoutMutation = <TError = LogoutAuthLogoutPostError, TContext = unknown>(settings?: {
    params?: UseMutationOptions<PostAuthLogoutHookData, TError, PostAuthLogoutMutationVariables, TContext>;
    request?: NonNullable<PostAuthLogoutMutationVariables>;
}) => useMutation({
    mutationKey: [postAuthLogoutMutationKey],
    mutationFn: async (params) => postAuthLogout({ ...settings?.request, ...params }),
    ...settings?.params
});