// This file is auto-generated by @hey-api/openapi-ts

import type { UseMutationOptions } from "@tanstack/react-query";

import { useMutation } from "@tanstack/react-query";

import type { LoginAuthLoginPostError } from "..//..//types.gen";

import { postAuthLogin } from "..//..//requests//auth//postAuthLogin.gen";

type PostAuthLoginHookData = Awaited<ReturnType<typeof postAuthLogin>>;

export const postAuthLoginMutationKey = "postAuthLoginMutationKey";

type PostAuthLoginMutationVariables = Parameters<typeof postAuthLogin>[0];

export const usePostAuthLoginMutation = <TError = LoginAuthLoginPostError, TContext = unknown>(settings?: {
    params?: UseMutationOptions<PostAuthLoginHookData, TError, PostAuthLoginMutationVariables, TContext>;
    request?: NonNullable<PostAuthLoginMutationVariables>;
}) => useMutation({
    mutationKey: [postAuthLoginMutationKey],
    mutationFn: async (params) => postAuthLogin({ ...settings?.request, ...params }),
    ...settings?.params
});