// This file is auto-generated by @hey-api/openapi-ts

import type { UseQueryOptions, DefaultError } from "@tanstack/react-query";

import { queryOptions, useQuery } from "@tanstack/react-query";

import { getBanner } from "..//..//requests//home//getBanner.gen";

type GetBannerHookData = Awaited<ReturnType<typeof getBanner>>;

export const getBannerQueryKey = "getBannerQueryKey";

export const getBannerQueryOptions = <TData = GetBannerHookData, TError = DefaultError>(settings?: {
    params?: Omit<UseQueryOptions<GetBannerHookData, TError, TData>, "queryKey">;
    request?: NonNullable<Parameters<typeof getBanner>[0]>;
}) => queryOptions({
    queryKey: [getBannerQueryKey, ...(!!settings?.request?.path ? [settings?.request?.path] : []), ...(!!settings?.request?.query ? [settings?.request?.query] : []), ...(!!settings?.request?.body ? [settings?.request?.body] : [])],
    queryFn: async () => getBanner({ ...settings?.request }),
    ...settings?.params
});

export const useGetBannerQuery = <TData = GetBannerHookData, TError = DefaultError>(...args: Parameters<typeof getBannerQueryOptions<TData, TError>>) => useQuery(getBannerQueryOptions<TData, TError>(...args));