// This file is auto-generated by @hey-api/openapi-ts

import type { UseSuspenseQueryOptions, DefaultError } from "@tanstack/react-query";

import { queryOptions, useSuspenseQuery } from "@tanstack/react-query";

import { getBanner } from "..//..//requests//home//getBanner.gen";

type GetBannerHookData = Awaited<ReturnType<typeof getBanner>>;

export const getBannerSuspenseQueryKey = "getBannerSuspenseQueryKey";

export const getBannerSuspenseQueryOptions = <TData = GetBannerHookData, TError = DefaultError>(settings?: {
    params?: Omit<UseSuspenseQueryOptions<GetBannerHookData, TError, TData>, "queryKey">;
    request?: NonNullable<Parameters<typeof getBanner>[0]>;
}) => queryOptions({
    queryKey: [getBannerSuspenseQueryKey, ...(!!settings?.request?.path ? [settings?.request?.path] : []), ...(!!settings?.request?.query ? [settings?.request?.query] : []), ...(!!settings?.request?.body ? [settings?.request?.body] : [])],
    queryFn: async () => getBanner({ ...settings?.request }),
    ...settings?.params
});

export const useGetBannerSuspenseQuery = <TData = GetBannerHookData, TError = DefaultError>(...args: Parameters<typeof getBannerSuspenseQueryOptions<TData, TError>>) => useSuspenseQuery(getBannerSuspenseQueryOptions<TData, TError>(...args));