// This file is auto-generated by @hey-api/openapi-ts

import type { UseQueryOptions, DefaultError } from "@tanstack/react-query";

import { queryOptions, useQuery } from "@tanstack/react-query";

import { getUpdates } from "..//..//requests//home//getUpdates.gen";

type GetUpdatesHookData = Awaited<ReturnType<typeof getUpdates>>;

export const getUpdatesQueryKey = "getUpdatesQueryKey";

export const getUpdatesQueryOptions = <TData = GetUpdatesHookData, TError = DefaultError>(settings?: {
    params?: Omit<UseQueryOptions<GetUpdatesHookData, TError, TData>, "queryKey">;
    request?: NonNullable<Parameters<typeof getUpdates>[0]>;
}) => queryOptions({
    queryKey: [getUpdatesQueryKey, ...(!!settings?.request?.path ? [settings?.request?.path] : []), ...(!!settings?.request?.query ? [settings?.request?.query] : []), ...(!!settings?.request?.body ? [settings?.request?.body] : [])],
    queryFn: async () => getUpdates({ ...settings?.request }),
    ...settings?.params
});

export const useGetUpdatesQuery = <TData = GetUpdatesHookData, TError = DefaultError>(...args: Parameters<typeof getUpdatesQueryOptions<TData, TError>>) => useQuery(getUpdatesQueryOptions<TData, TError>(...args));