// This file is auto-generated by @hey-api/openapi-ts

import type { UseMutationOptions, DefaultError } from "@tanstack/react-query";

import { useMutation } from "@tanstack/react-query";

import { getBanner } from "..//..//requests//home//getBanner.gen";

type GetBannerHookData = Awaited<ReturnType<typeof getBanner>>;

export const getBannerMutationKey = "getBannerMutationKey";

type GetBannerMutationVariables = Parameters<typeof getBanner>[0];

export const useGetBannerMutation = <TError = DefaultError, TContext = unknown>(settings?: {
    params?: UseMutationOptions<GetBannerHookData, TError, GetBannerMutationVariables, TContext>;
    request?: NonNullable<GetBannerMutationVariables>;
}) => useMutation({
    mutationKey: [getBannerMutationKey],
    mutationFn: async (params) => getBanner({ ...settings?.request, ...params }),
    ...settings?.params
});