// This file is auto-generated by @hey-api/openapi-ts

import type { UseMutationOptions, DefaultError } from "@tanstack/react-query";

import { useMutation } from "@tanstack/react-query";

import { getUpdates } from "..//..//requests//home//getUpdates.gen";

type GetUpdatesHookData = Awaited<ReturnType<typeof getUpdates>>;

export const getUpdatesMutationKey = "getUpdatesMutationKey";

type GetUpdatesMutationVariables = Parameters<typeof getUpdates>[0];

export const useGetUpdatesMutation = <TError = DefaultError, TContext = unknown>(settings?: {
    params?: UseMutationOptions<GetUpdatesHookData, TError, GetUpdatesMutationVariables, TContext>;
    request?: NonNullable<GetUpdatesMutationVariables>;
}) => useMutation({
    mutationKey: [getUpdatesMutationKey],
    mutationFn: async (params) => getUpdates({ ...settings?.request, ...params }),
    ...settings?.params
});