// This file is auto-generated by @hey-api/openapi-ts

import type { UseSuspenseQueryOptions, DefaultError } from "@tanstack/react-query";

import { queryOptions, useSuspenseQuery } from "@tanstack/react-query";

import { getUpdates } from "..//..//requests//home//getUpdates.gen";

type GetUpdatesHookData = Awaited<ReturnType<typeof getUpdates>>;

export const getUpdatesSuspenseQueryKey = "getUpdatesSuspenseQueryKey";

export const getUpdatesSuspenseQueryOptions = <TData = GetUpdatesHookData, TError = DefaultError>(settings?: {
    params?: Omit<UseSuspenseQueryOptions<GetUpdatesHookData, TError, TData>, "queryKey">;
    request?: NonNullable<Parameters<typeof getUpdates>[0]>;
}) => queryOptions({
    queryKey: [getUpdatesSuspenseQueryKey, ...(!!settings?.request?.path ? [settings?.request?.path] : []), ...(!!settings?.request?.query ? [settings?.request?.query] : []), ...(!!settings?.request?.body ? [settings?.request?.body] : [])],
    queryFn: async () => getUpdates({ ...settings?.request }),
    ...settings?.params
});

export const useGetUpdatesSuspenseQuery = <TData = GetUpdatesHookData, TError = DefaultError>(...args: Parameters<typeof getUpdatesSuspenseQueryOptions<TData, TError>>) => useSuspenseQuery(getUpdatesSuspenseQueryOptions<TData, TError>(...args));