// This file is auto-generated by @hey-api/openapi-ts

import type { FetchesRequestParams, ApicraftFetchesResponse } from '@siberiacancode/apicraft';

import type { GetBannerBannerGetData, GetBannerBannerGetResponse } from '..//..//types.gen';

import { instance } from '../../instance.gen';

export type GetBannerRequestParams = FetchesRequestParams<GetBannerBannerGetData> | void;

export const getBanner = ({ config }: GetBannerRequestParams = {}): Promise<
  ApicraftFetchesResponse<GetBannerBannerGetResponse>
> =>
  instance.call('GET', '/banner', {
    ...config
  });
