// This file is auto-generated by @hey-api/openapi-ts

import type { FetchesRequestParams, ApicraftFetchesResponse } from '@siberiacancode/apicraft';

import type { GetUpdatesUpdatesGetData, GetUpdatesUpdatesGetResponse } from '..//..//types.gen';

import { instance } from '../../instance.gen';

export type GetUpdatesRequestParams = FetchesRequestParams<GetUpdatesUpdatesGetData> | void;

export const getUpdates = ({ config }: GetUpdatesRequestParams = {}): Promise<
  ApicraftFetchesResponse<GetUpdatesUpdatesGetResponse>
> =>
  instance.call('GET', '/updates', {
    ...config
  });
