// This file is auto-generated by @hey-api/openapi-ts

import type { FetchesRequestParams, ApicraftFetchesResponse } from '@siberiacancode/apicraft';

import type {
  GetProfileImageProfileImagesPathnameGetData,
  GetProfileImageProfileImagesPathnameGetError
} from '..//..//types.gen';

import { instance } from '../../instance.gen';

export type GetProfileImageByPathnameRequestParams =
  FetchesRequestParams<GetProfileImageProfileImagesPathnameGetData>;

export const getProfileImageByPathname = ({
  config,
  path
}: GetProfileImageByPathnameRequestParams): Promise<
  ApicraftFetchesResponse<never, GetProfileImageProfileImagesPathnameGetError>
> =>
  instance.call('GET', `/profile/images/${path.pathname}`, {
    ...config
  });
