// This file is auto-generated by @hey-api/openapi-ts

import type { FetchesRequestParams, ApicraftFetchesResponse } from '@siberiacancode/apicraft';

import type {
  GetProfileProfileUsernameGetData,
  GetProfileProfileUsernameGetResponse,
  GetProfileProfileUsernameGetError
} from '..//..//types.gen';

import { instance } from '../../instance.gen';

export type GetProfileByUsernameRequestParams =
  FetchesRequestParams<GetProfileProfileUsernameGetData>;

export const getProfileByUsername = ({
  config,
  path
}: GetProfileByUsernameRequestParams): Promise<
  ApicraftFetchesResponse<GetProfileProfileUsernameGetResponse, GetProfileProfileUsernameGetError>
> =>
  instance.call('GET', `/profile/${path.username}`, {
    ...config
  });
