// This file is auto-generated by @hey-api/openapi-ts

import type { FetchesRequestParams, ApicraftFetchesResponse } from '@siberiacancode/apicraft';

import type {
  UpdateProfileProfileMePatchData,
  UpdateProfileProfileMePatchResponse,
  UpdateProfileProfileMePatchError
} from '..//..//types.gen';

import { instance } from '../../instance.gen';

export type PatchProfileMeRequestParams = FetchesRequestParams<UpdateProfileProfileMePatchData>;

export const patchProfileMe = ({
  config,
  body
}: PatchProfileMeRequestParams): Promise<
  ApicraftFetchesResponse<UpdateProfileProfileMePatchResponse, UpdateProfileProfileMePatchError>
> =>
  instance.call('PATCH', '/profile/me', {
    body,
    ...config
  });
