// This file is auto-generated by @hey-api/openapi-ts

import type { FetchesRequestParams, ApicraftFetchesResponse } from '@siberiacancode/apicraft';

import type {
  UploadProfileImageProfileMeImageTypePostData,
  UploadProfileImageProfileMeImageTypePostResponse,
  UploadProfileImageProfileMeImageTypePostError
} from '..//..//types.gen';

import { instance } from '../../instance.gen';

export type PostProfileMeByImageTypeRequestParams =
  FetchesRequestParams<UploadProfileImageProfileMeImageTypePostData>;

export const postProfileMeByImageType = ({
  config,
  body,
  path
}: PostProfileMeByImageTypeRequestParams): Promise<
  ApicraftFetchesResponse<
    UploadProfileImageProfileMeImageTypePostResponse,
    UploadProfileImageProfileMeImageTypePostError
  >
> =>
  instance.call('POST', `/profile/me/${path.image_type}`, {
    body,
    ...config
  });
