/* eslint-disable node/prefer-global/process */

export const METADATA = {
  NAME: 'letter to u!',
  URL: process.env.BASE_URL || 'http://localhost:3000',
  DESCRIPTION: 'letter to u! - Современный сервис просмотра аниме',
  KEYWORDS: [
    'letter to u!',
    'anime',
    'anime online',
    'watch anime',
    'watch anime online',
    'anime free',
    'anime HD',
    'anime with subtitles',
    'anime dubbed',
    'anime streaming',
    'best anime site',
    'anime series',
    'anime movies',
    'anime 2024',
    'аниме',
    'аниме онлайн',
    'смотреть аниме',
    'смотреть аниме онлайн',
    'аниме бесплатно',
    'аниме в HD',
    'аниме с субтитрами',
    'аниме с озвучкой',
    'аниме стриминг',
    'лучший сайт аниме',
    'аниме сериалы',
    'аниме фильмы',
    'аниме 2024',
    'смотреть аниме онлайн бесплатно',
    'аниме онлайн в хорошем качестве',
    'бесплатное аниме онлайн',
    'аниме без регистрации',
    'аниме на русском',
    'аниме с русской озвучкой',
    'аниме с русскими субтитрами',
    'новинки аниме',
    'популярное аниме',
    'топ аниме',
    'аниме жанры',
    'аниме по годам',
    'аниме по алфавиту'
  ]
};
