// This file is auto-generated by @hey-api/openapi-ts

/**
 * AnimeSchema
 */
export type AnimeSchema = {
    /**
     * Id
     */
    id: string;
    /**
     * Slug
     */
    slug: string;
    /**
     * Shikimori Id
     */
    shikimori_id?: number | null;
    /**
     * Age Rating
     */
    age_rating: number | null;
    /**
     * Title
     */
    title: string;
    /**
     * Description
     */
    description: string | null;
    /**
     * Poster
     */
    poster: string | null;
    /**
     * Tags
     */
    tags: Array<TagsScheme> | null;
    /**
     * Blocked Countries
     */
    blocked_countries: Array<string> | null;
    /**
     * Year
     */
    year: number | null;
    /**
     * Duration
     */
    duration: number | null;
    /**
     * Episodes Count
     */
    episodes_count: number | null;
    /**
     * Kinopoisk Rating
     */
    kinopoisk_rating: number | null;
    /**
     * Created At
     */
    created_at: string | null;
    /**
     * Updated At
     */
    updated_at: string | null;
    /**
     * Screenshots
     */
    screenshots: Array<string> | null;
    /**
     * Countries
     */
    countries: Array<string> | null;
    /**
     * Iframe Url
     */
    iframe_url?: string | null;
    /**
     * Type
     */
    type: string | null;
    /**
     * Anime Status
     */
    anime_status?: string | null;
    /**
     * Anime Studios
     */
    anime_studios?: Array<string> | null;
    /**
     * Translations
     */
    translations: Array<AnimeTranslationSchema> | null;
    /**
     * Shikimori Rating
     */
    shikimori_rating?: number | null;
};

/**
 * AnimeTranslationSchema
 */
export type AnimeTranslationSchema = {
    /**
     * Id
     */
    id: number;
    /**
     * Title
     */
    title: string;
    /**
     * Episodes Count
     */
    episodes_count: number | null;
};

/**
 * Body_upload_profile_image_profile_me__image_type__post
 */
export type BodyUploadProfileImageProfileMeImageTypePost = {
    /**
     * Image
     */
    image: string;
};

/**
 * EpisodeSchema
 */
export type EpisodeSchema = {
    /**
     * Episode
     */
    episode: number;
    /**
     * Link
     */
    link: string;
};

/**
 * GenreAnimeListSchema
 */
export type GenreAnimeListSchema = {
    /**
     * Results
     */
    results: Array<ShortAnimeSchema>;
    /**
     * Next Page
     */
    next_page?: string | null;
};

/**
 * GenreSchema
 */
export type GenreSchema = {
    /**
     * Slug
     */
    slug: string;
    /**
     * Title
     */
    title: string;
    /**
     * Count
     */
    count?: number | null;
};

/**
 * HTTPValidationError
 */
export type HttpValidationError = {
    /**
     * Detail
     */
    detail?: Array<ValidationError>;
};

/**
 * LoginSchema
 */
export type LoginSchema = {
    /**
     * Email
     */
    email: string;
    /**
     * Password
     */
    password: string;
};

/**
 * PlayerSchema
 */
export type PlayerSchema = {
    /**
     * Shikimori Id
     */
    shikimori_id: number | null;
    /**
     * Iframe Url
     */
    iframe_url: string;
    /**
     * Translations
     */
    translations: Array<PlayerTranslationSchema>;
};

/**
 * PlayerTranslationSchema
 */
export type PlayerTranslationSchema = {
    /**
     * Id
     */
    id: number;
    /**
     * Title
     */
    title: string;
    /**
     * Type
     */
    type?: string | null;
    /**
     * Quality
     */
    quality?: string | null;
    /**
     * Episodes Count
     */
    episodes_count?: number | null;
};

/**
 * PublicUserSchema
 * Профиль, видимый другим пользователям — без почты.
 */
export type PublicUserSchema = {
    /**
     * Id
     */
    id: number;
    /**
     * Username
     */
    username: string;
    /**
     * Avatar
     */
    avatar?: string;
    /**
     * Banner
     */
    banner?: string;
};

/**
 * RegisterSchema
 */
export type RegisterSchema = {
    /**
     * Username
     */
    username: string;
    /**
     * Email
     */
    email: string;
    /**
     * Password
     */
    password: string;
};

/**
 * ShortAnimeSchema
 */
export type ShortAnimeSchema = {
    /**
     * Id
     */
    id: string;
    /**
     * Slug
     */
    slug: string;
    /**
     * Poster
     */
    poster: string | null;
    /**
     * Title
     */
    title: string;
    /**
     * Type
     */
    type?: string | null;
    /**
     * Year
     */
    year?: number | null;
    /**
     * Anime Status
     */
    anime_status?: string | null;
};

/**
 * SwiperBannerSchema
 */
export type SwiperBannerSchema = {
    /**
     * Id
     */
    id: string;
    /**
     * Slug
     */
    slug: string;
    /**
     * Age Rating
     */
    age_rating?: number | null;
    /**
     * Anime Status
     */
    anime_status?: string | null;
    /**
     * Type
     */
    type?: string | null;
    /**
     * Title
     */
    title: string;
    /**
     * Description
     */
    description: string;
    /**
     * Poster
     */
    poster: string;
    /**
     * Shikimori Rating
     */
    shikimori_rating?: number | null;
};

/**
 * TagsScheme
 */
export type TagsScheme = {
    /**
     * Id
     */
    id: number;
    /**
     * Genre
     */
    genre: string;
};

/**
 * UpdateProfileSchema
 */
export type UpdateProfileSchema = {
    /**
     * Email
     */
    email?: string | null;
    /**
     * Current Password
     */
    current_password?: string | null;
    /**
     * New Password
     */
    new_password?: string | null;
};

/**
 * UserSchema
 */
export type UserSchema = {
    /**
     * Id
     */
    id: number;
    /**
     * Username
     */
    username: string;
    /**
     * Email
     */
    email: string;
    /**
     * Avatar
     */
    avatar?: string;
    /**
     * Banner
     */
    banner?: string;
};

/**
 * ValidationError
 */
export type ValidationError = {
    /**
     * Location
     */
    loc: Array<string | number>;
    /**
     * Message
     */
    msg: string;
    /**
     * Error Type
     */
    type: string;
    /**
     * Input
     */
    input?: unknown;
    /**
     * Context
     */
    ctx?: {
        [key: string]: unknown;
    };
};

export type GetPopularsPopularsGetData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/populars';
};

export type GetPopularsPopularsGetResponses = {
    /**
     * Response Get Populars Populars Get
     * Successful Response
     */
    200: Array<ShortAnimeSchema>;
};

export type GetPopularsPopularsGetResponse = GetPopularsPopularsGetResponses[keyof GetPopularsPopularsGetResponses];

export type GetAnimeTitleGetData = {
    body?: never;
    path?: never;
    query: {
        /**
         * Slug
         */
        slug: string;
    };
    url: '/title';
};

export type GetAnimeTitleGetErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type GetAnimeTitleGetError = GetAnimeTitleGetErrors[keyof GetAnimeTitleGetErrors];

export type GetAnimeTitleGetResponses = {
    /**
     * Successful Response
     */
    200: AnimeSchema;
};

export type GetAnimeTitleGetResponse = GetAnimeTitleGetResponses[keyof GetAnimeTitleGetResponses];

export type GetPlayerTitlePlayerGetData = {
    body?: never;
    path?: never;
    query: {
        /**
         * Slug
         */
        slug: string;
    };
    url: '/title/player';
};

export type GetPlayerTitlePlayerGetErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type GetPlayerTitlePlayerGetError = GetPlayerTitlePlayerGetErrors[keyof GetPlayerTitlePlayerGetErrors];

export type GetPlayerTitlePlayerGetResponses = {
    /**
     * Successful Response
     */
    200: PlayerSchema;
};

export type GetPlayerTitlePlayerGetResponse = GetPlayerTitlePlayerGetResponses[keyof GetPlayerTitlePlayerGetResponses];

export type SearchAnimeShortSearchGetData = {
    body?: never;
    path?: never;
    query: {
        /**
         * Search
         */
        search: string;
        /**
         * Limit
         */
        limit?: number;
    };
    url: '/short-search/';
};

export type SearchAnimeShortSearchGetErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type SearchAnimeShortSearchGetError = SearchAnimeShortSearchGetErrors[keyof SearchAnimeShortSearchGetErrors];

export type SearchAnimeShortSearchGetResponses = {
    /**
     * Response Search Anime Short Search  Get
     * Successful Response
     */
    200: Array<ShortAnimeSchema>;
};

export type SearchAnimeShortSearchGetResponse = SearchAnimeShortSearchGetResponses[keyof SearchAnimeShortSearchGetResponses];

export type GetTranslationTranslationGetData = {
    body?: never;
    path?: never;
    query: {
        /**
         * Shiki Id
         */
        shiki_id: number;
        /**
         * Translation Id
         */
        translation_id: number;
    };
    url: '/translation';
};

export type GetTranslationTranslationGetErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type GetTranslationTranslationGetError = GetTranslationTranslationGetErrors[keyof GetTranslationTranslationGetErrors];

export type GetTranslationTranslationGetResponses = {
    /**
     * Response Get Translation Translation Get
     * Successful Response
     */
    200: Array<EpisodeSchema>;
};

export type GetTranslationTranslationGetResponse = GetTranslationTranslationGetResponses[keyof GetTranslationTranslationGetResponses];

export type RegisterAuthRegisterPostData = {
    body: RegisterSchema;
    path?: never;
    query?: never;
    url: '/auth/register';
};

export type RegisterAuthRegisterPostErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type RegisterAuthRegisterPostError = RegisterAuthRegisterPostErrors[keyof RegisterAuthRegisterPostErrors];

export type RegisterAuthRegisterPostResponses = {
    /**
     * Successful Response
     */
    201: UserSchema;
};

export type RegisterAuthRegisterPostResponse = RegisterAuthRegisterPostResponses[keyof RegisterAuthRegisterPostResponses];

export type LoginAuthLoginPostData = {
    body: LoginSchema;
    path?: never;
    query?: never;
    url: '/auth/login';
};

export type LoginAuthLoginPostErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type LoginAuthLoginPostError = LoginAuthLoginPostErrors[keyof LoginAuthLoginPostErrors];

export type LoginAuthLoginPostResponses = {
    /**
     * Successful Response
     */
    200: UserSchema;
};

export type LoginAuthLoginPostResponse = LoginAuthLoginPostResponses[keyof LoginAuthLoginPostResponses];

export type MeAuthMeGetData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/auth/me';
};

export type MeAuthMeGetErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type MeAuthMeGetError = MeAuthMeGetErrors[keyof MeAuthMeGetErrors];

export type MeAuthMeGetResponses = {
    /**
     * Successful Response
     */
    200: UserSchema;
};

export type MeAuthMeGetResponse = MeAuthMeGetResponses[keyof MeAuthMeGetResponses];

export type LogoutAuthLogoutPostData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/auth/logout';
};

export type LogoutAuthLogoutPostErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type LogoutAuthLogoutPostError = LogoutAuthLogoutPostErrors[keyof LogoutAuthLogoutPostErrors];

export type LogoutAuthLogoutPostResponses = {
    /**
     * Successful Response
     */
    204: void;
};

export type LogoutAuthLogoutPostResponse = LogoutAuthLogoutPostResponses[keyof LogoutAuthLogoutPostResponses];

export type UpdateProfileProfileMePatchData = {
    body: UpdateProfileSchema;
    path?: never;
    query?: never;
    url: '/profile/me';
};

export type UpdateProfileProfileMePatchErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type UpdateProfileProfileMePatchError = UpdateProfileProfileMePatchErrors[keyof UpdateProfileProfileMePatchErrors];

export type UpdateProfileProfileMePatchResponses = {
    /**
     * Successful Response
     */
    200: UserSchema;
};

export type UpdateProfileProfileMePatchResponse = UpdateProfileProfileMePatchResponses[keyof UpdateProfileProfileMePatchResponses];

export type UploadProfileImageProfileMeImageTypePostData = {
    body: BodyUploadProfileImageProfileMeImageTypePost;
    path: {
        /**
         * Image Type
         */
        image_type: string;
    };
    query?: never;
    url: '/profile/me/{image_type}';
};

export type UploadProfileImageProfileMeImageTypePostErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type UploadProfileImageProfileMeImageTypePostError = UploadProfileImageProfileMeImageTypePostErrors[keyof UploadProfileImageProfileMeImageTypePostErrors];

export type UploadProfileImageProfileMeImageTypePostResponses = {
    /**
     * Successful Response
     */
    200: UserSchema;
};

export type UploadProfileImageProfileMeImageTypePostResponse = UploadProfileImageProfileMeImageTypePostResponses[keyof UploadProfileImageProfileMeImageTypePostResponses];

export type GetProfileImageProfileImagesPathnameGetData = {
    body?: never;
    path: {
        /**
         * Pathname
         */
        pathname: string;
    };
    query?: never;
    url: '/profile/images/{pathname}';
};

export type GetProfileImageProfileImagesPathnameGetErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type GetProfileImageProfileImagesPathnameGetError = GetProfileImageProfileImagesPathnameGetErrors[keyof GetProfileImageProfileImagesPathnameGetErrors];

export type GetProfileImageProfileImagesPathnameGetResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};

export type GetProfileProfileUsernameGetData = {
    body?: never;
    path: {
        /**
         * Username
         */
        username: string;
    };
    query?: never;
    url: '/profile/{username}';
};

export type GetProfileProfileUsernameGetErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type GetProfileProfileUsernameGetError = GetProfileProfileUsernameGetErrors[keyof GetProfileProfileUsernameGetErrors];

export type GetProfileProfileUsernameGetResponses = {
    /**
     * Successful Response
     */
    200: PublicUserSchema;
};

export type GetProfileProfileUsernameGetResponse = GetProfileProfileUsernameGetResponses[keyof GetProfileProfileUsernameGetResponses];

export type GetGenresGenresGetData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/genres';
};

export type GetGenresGenresGetResponses = {
    /**
     * Response Get Genres Genres Get
     * Successful Response
     */
    200: Array<GenreSchema>;
};

export type GetGenresGenresGetResponse = GetGenresGenresGetResponses[keyof GetGenresGenresGetResponses];

export type GetAnimeByGenreGenresSlugAnimeGetData = {
    body?: never;
    path: {
        /**
         * Slug
         */
        slug: string;
    };
    query?: {
        /**
         * Next
         */
        next?: string | null;
    };
    url: '/genres/{slug}/anime';
};

export type GetAnimeByGenreGenresSlugAnimeGetErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type GetAnimeByGenreGenresSlugAnimeGetError = GetAnimeByGenreGenresSlugAnimeGetErrors[keyof GetAnimeByGenreGenresSlugAnimeGetErrors];

export type GetAnimeByGenreGenresSlugAnimeGetResponses = {
    /**
     * Successful Response
     */
    200: GenreAnimeListSchema;
};

export type GetAnimeByGenreGenresSlugAnimeGetResponse = GetAnimeByGenreGenresSlugAnimeGetResponses[keyof GetAnimeByGenreGenresSlugAnimeGetResponses];

export type GetBannerBannerGetData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/banner';
};

export type GetBannerBannerGetResponses = {
    /**
     * Response Get Banner Banner Get
     * Successful Response
     */
    200: Array<SwiperBannerSchema>;
};

export type GetBannerBannerGetResponse = GetBannerBannerGetResponses[keyof GetBannerBannerGetResponses];

export type GetUpdatesUpdatesGetData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/updates';
};

export type GetUpdatesUpdatesGetResponses = {
    /**
     * Response Get Updates Updates Get
     * Successful Response
     */
    200: Array<ShortAnimeSchema>;
};

export type GetUpdatesUpdatesGetResponse = GetUpdatesUpdatesGetResponses[keyof GetUpdatesUpdatesGetResponses];

export type RootGetData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/';
};

export type RootGetResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};

export type ClientOptions = {
    baseUrl: `${string}://${string}` | (string & {});
};