// This file is auto-generated by @hey-api/openapi-ts

import type { FetchesRequestParams, ApicraftFetchesResponse } from '@siberiacancode/apicraft';

import type { MeAuthMeGetData, MeAuthMeGetResponse, MeAuthMeGetError } from '..//..//types.gen';

import { instance } from '../../instance.gen';

export type GetAuthMeRequestParams = FetchesRequestParams<MeAuthMeGetData> | void;

export const getAuthMe = ({ config }: GetAuthMeRequestParams = {}): Promise<
  ApicraftFetchesResponse<MeAuthMeGetResponse, MeAuthMeGetError>
> =>
  instance.call('GET', '/auth/me', {
    ...config
  });
