// This file is auto-generated by @hey-api/openapi-ts

import type { FetchesRequestParams, ApicraftFetchesResponse } from '@siberiacancode/apicraft';

import type {
  LogoutAuthLogoutPostData,
  LogoutAuthLogoutPostResponse,
  LogoutAuthLogoutPostError
} from '..//..//types.gen';

import { instance } from '../../instance.gen';

export type PostAuthLogoutRequestParams = FetchesRequestParams<LogoutAuthLogoutPostData> | void;

export const postAuthLogout = ({ config }: PostAuthLogoutRequestParams = {}): Promise<
  ApicraftFetchesResponse<LogoutAuthLogoutPostResponse, LogoutAuthLogoutPostError>
> =>
  instance.call('POST', '/auth/logout', {
    ...config
  });
