// This file is auto-generated by @hey-api/openapi-ts

import type { FetchesRequestParams, ApicraftFetchesResponse } from '@siberiacancode/apicraft';

import type {
  RegisterAuthRegisterPostData,
  RegisterAuthRegisterPostResponse,
  RegisterAuthRegisterPostError
} from '..//..//types.gen';

import { instance } from '../../instance.gen';

export type PostAuthRegisterRequestParams = FetchesRequestParams<RegisterAuthRegisterPostData>;

export const postAuthRegister = ({
  config,
  body
}: PostAuthRegisterRequestParams): Promise<
  ApicraftFetchesResponse<RegisterAuthRegisterPostResponse, RegisterAuthRegisterPostError>
> =>
  instance.call('POST', '/auth/register', {
    body,
    ...config
  });
