// This file is auto-generated by @hey-api/openapi-ts

import type { FetchesRequestParams, ApicraftFetchesResponse } from '@siberiacancode/apicraft';

import type {
  LoginAuthLoginPostData,
  LoginAuthLoginPostResponse,
  LoginAuthLoginPostError
} from '..//..//types.gen';

import { instance } from '../../instance.gen';

export type PostAuthLoginRequestParams = FetchesRequestParams<LoginAuthLoginPostData>;

export const postAuthLogin = ({
  config,
  body
}: PostAuthLoginRequestParams): Promise<
  ApicraftFetchesResponse<LoginAuthLoginPostResponse, LoginAuthLoginPostError>
> =>
  instance.call('POST', '/auth/login', {
    body,
    ...config
  });
