// This file is auto-generated by @hey-api/openapi-ts

import type { UseSuspenseQueryOptions } from "@tanstack/react-query";

import { queryOptions, useSuspenseQuery } from "@tanstack/react-query";

import type { GetAnimeTitleGetError } from "..//..//types.gen";

import { getTitle } from "..//..//requests//searchAnime//getTitle.gen";

type GetTitleHookData = Awaited<ReturnType<typeof getTitle>>;

export const getTitleSuspenseQueryKey = "getTitleSuspenseQueryKey";

export const getTitleSuspenseQueryOptions = <TData = GetTitleHookData, TError = GetAnimeTitleGetError>(settings: {
    params?: Omit<UseSuspenseQueryOptions<GetTitleHookData, TError, TData>, "queryKey">;
    request: NonNullable<Parameters<typeof getTitle>[0]>;
}) => queryOptions({
    queryKey: [getTitleSuspenseQueryKey, ...(!!settings.request.path ? [settings.request.path] : []), ...(!!settings.request.query ? [settings.request.query] : []), ...(!!settings.request.body ? [settings.request.body] : [])],
    queryFn: async () => getTitle({ ...settings.request }),
    ...settings.params
});

export const useGetTitleSuspenseQuery = <TData = GetTitleHookData, TError = GetAnimeTitleGetError>(...args: Parameters<typeof getTitleSuspenseQueryOptions<TData, TError>>) => useSuspenseQuery(getTitleSuspenseQueryOptions<TData, TError>(...args));