// This file is auto-generated by @hey-api/openapi-ts

import type { UseMutationOptions } from "@tanstack/react-query";

import { useMutation } from "@tanstack/react-query";

import type { GetAnimeTitleGetError } from "..//..//types.gen";

import { getTitle } from "..//..//requests//searchAnime//getTitle.gen";

type GetTitleHookData = Awaited<ReturnType<typeof getTitle>>;

export const getTitleMutationKey = "getTitleMutationKey";

type GetTitleMutationVariables = Parameters<typeof getTitle>[0];

export const useGetTitleMutation = <TError = GetAnimeTitleGetError, TContext = unknown>(settings?: {
    params?: UseMutationOptions<GetTitleHookData, TError, GetTitleMutationVariables, TContext>;
    request?: NonNullable<GetTitleMutationVariables>;
}) => useMutation({
    mutationKey: [getTitleMutationKey],
    mutationFn: async (params) => getTitle({ ...settings?.request, ...params }),
    ...settings?.params
});