// This file is auto-generated by @hey-api/openapi-ts

import type { UseQueryOptions } from "@tanstack/react-query";

import { queryOptions, useQuery } from "@tanstack/react-query";

import type { GetAnimeTitleGetError } from "..//..//types.gen";

import { getTitle } from "..//..//requests//searchAnime//getTitle.gen";

type GetTitleHookData = Awaited<ReturnType<typeof getTitle>>;

export const getTitleQueryKey = "getTitleQueryKey";

export const getTitleQueryOptions = <TData = GetTitleHookData, TError = GetAnimeTitleGetError>(settings: {
    params?: Omit<UseQueryOptions<GetTitleHookData, TError, TData>, "queryKey">;
    request: NonNullable<Parameters<typeof getTitle>[0]>;
}) => queryOptions({
    queryKey: [getTitleQueryKey, ...(!!settings.request.path ? [settings.request.path] : []), ...(!!settings.request.query ? [settings.request.query] : []), ...(!!settings.request.body ? [settings.request.body] : [])],
    queryFn: async () => getTitle({ ...settings.request }),
    ...settings.params
});

export const useGetTitleQuery = <TData = GetTitleHookData, TError = GetAnimeTitleGetError>(...args: Parameters<typeof getTitleQueryOptions<TData, TError>>) => useQuery(getTitleQueryOptions<TData, TError>(...args));