// This file is auto-generated by @hey-api/openapi-ts

import type { UseMutationOptions } from "@tanstack/react-query";

import { useMutation } from "@tanstack/react-query";

import type { GetPlayerTitlePlayerGetError } from "..//..//types.gen";

import { getTitlePlayer } from "..//..//requests//searchAnime//getTitlePlayer.gen";

type GetTitlePlayerHookData = Awaited<ReturnType<typeof getTitlePlayer>>;

export const getTitlePlayerMutationKey = "getTitlePlayerMutationKey";

type GetTitlePlayerMutationVariables = Parameters<typeof getTitlePlayer>[0];

export const useGetTitlePlayerMutation = <TError = GetPlayerTitlePlayerGetError, TContext = unknown>(settings?: {
    params?: UseMutationOptions<GetTitlePlayerHookData, TError, GetTitlePlayerMutationVariables, TContext>;
    request?: NonNullable<GetTitlePlayerMutationVariables>;
}) => useMutation({
    mutationKey: [getTitlePlayerMutationKey],
    mutationFn: async (params) => getTitlePlayer({ ...settings?.request, ...params }),
    ...settings?.params
});