// This file is auto-generated by @hey-api/openapi-ts

import type { UseQueryOptions } from "@tanstack/react-query";

import { queryOptions, useQuery } from "@tanstack/react-query";

import type { GetPlayerTitlePlayerGetError } from "..//..//types.gen";

import { getTitlePlayer } from "..//..//requests//searchAnime//getTitlePlayer.gen";

type GetTitlePlayerHookData = Awaited<ReturnType<typeof getTitlePlayer>>;

export const getTitlePlayerQueryKey = "getTitlePlayerQueryKey";

export const getTitlePlayerQueryOptions = <TData = GetTitlePlayerHookData, TError = GetPlayerTitlePlayerGetError>(settings: {
    params?: Omit<UseQueryOptions<GetTitlePlayerHookData, TError, TData>, "queryKey">;
    request: NonNullable<Parameters<typeof getTitlePlayer>[0]>;
}) => queryOptions({
    queryKey: [getTitlePlayerQueryKey, ...(!!settings.request.path ? [settings.request.path] : []), ...(!!settings.request.query ? [settings.request.query] : []), ...(!!settings.request.body ? [settings.request.body] : [])],
    queryFn: async () => getTitlePlayer({ ...settings.request }),
    ...settings.params
});

export const useGetTitlePlayerQuery = <TData = GetTitlePlayerHookData, TError = GetPlayerTitlePlayerGetError>(...args: Parameters<typeof getTitlePlayerQueryOptions<TData, TError>>) => useQuery(getTitlePlayerQueryOptions<TData, TError>(...args));