// This file is auto-generated by @hey-api/openapi-ts

import type { UseSuspenseQueryOptions } from "@tanstack/react-query";

import { queryOptions, useSuspenseQuery } from "@tanstack/react-query";

import type { GetPlayerTitlePlayerGetError } from "..//..//types.gen";

import { getTitlePlayer } from "..//..//requests//searchAnime//getTitlePlayer.gen";

type GetTitlePlayerHookData = Awaited<ReturnType<typeof getTitlePlayer>>;

export const getTitlePlayerSuspenseQueryKey = "getTitlePlayerSuspenseQueryKey";

export const getTitlePlayerSuspenseQueryOptions = <TData = GetTitlePlayerHookData, TError = GetPlayerTitlePlayerGetError>(settings: {
    params?: Omit<UseSuspenseQueryOptions<GetTitlePlayerHookData, TError, TData>, "queryKey">;
    request: NonNullable<Parameters<typeof getTitlePlayer>[0]>;
}) => queryOptions({
    queryKey: [getTitlePlayerSuspenseQueryKey, ...(!!settings.request.path ? [settings.request.path] : []), ...(!!settings.request.query ? [settings.request.query] : []), ...(!!settings.request.body ? [settings.request.body] : [])],
    queryFn: async () => getTitlePlayer({ ...settings.request }),
    ...settings.params
});

export const useGetTitlePlayerSuspenseQuery = <TData = GetTitlePlayerHookData, TError = GetPlayerTitlePlayerGetError>(...args: Parameters<typeof getTitlePlayerSuspenseQueryOptions<TData, TError>>) => useSuspenseQuery(getTitlePlayerSuspenseQueryOptions<TData, TError>(...args));