// This file is auto-generated by @hey-api/openapi-ts

import type { UseQueryOptions, DefaultError } from "@tanstack/react-query";

import { queryOptions, useQuery } from "@tanstack/react-query";

import { getGenres } from "..//..//requests//genres//getGenres.gen";

type GetGenresHookData = Awaited<ReturnType<typeof getGenres>>;

export const getGenresQueryKey = "getGenresQueryKey";

export const getGenresQueryOptions = <TData = GetGenresHookData, TError = DefaultError>(settings?: {
    params?: Omit<UseQueryOptions<GetGenresHookData, TError, TData>, "queryKey">;
    request?: NonNullable<Parameters<typeof getGenres>[0]>;
}) => queryOptions({
    queryKey: [getGenresQueryKey, ...(!!settings?.request?.path ? [settings?.request?.path] : []), ...(!!settings?.request?.query ? [settings?.request?.query] : []), ...(!!settings?.request?.body ? [settings?.request?.body] : [])],
    queryFn: async () => getGenres({ ...settings?.request }),
    ...settings?.params
});

export const useGetGenresQuery = <TData = GetGenresHookData, TError = DefaultError>(...args: Parameters<typeof getGenresQueryOptions<TData, TError>>) => useQuery(getGenresQueryOptions<TData, TError>(...args));