// This file is auto-generated by @hey-api/openapi-ts

import type { UseMutationOptions, DefaultError } from "@tanstack/react-query";

import { useMutation } from "@tanstack/react-query";

import { getGenres } from "..//..//requests//genres//getGenres.gen";

type GetGenresHookData = Awaited<ReturnType<typeof getGenres>>;

export const getGenresMutationKey = "getGenresMutationKey";

type GetGenresMutationVariables = Parameters<typeof getGenres>[0];

export const useGetGenresMutation = <TError = DefaultError, TContext = unknown>(settings?: {
    params?: UseMutationOptions<GetGenresHookData, TError, GetGenresMutationVariables, TContext>;
    request?: NonNullable<GetGenresMutationVariables>;
}) => useMutation({
    mutationKey: [getGenresMutationKey],
    mutationFn: async (params) => getGenres({ ...settings?.request, ...params }),
    ...settings?.params
});