// This file is auto-generated by @hey-api/openapi-ts

import type { UseSuspenseQueryOptions, DefaultError } from "@tanstack/react-query";

import { queryOptions, useSuspenseQuery } from "@tanstack/react-query";

import { getGenres } from "..//..//requests//genres//getGenres.gen";

type GetGenresHookData = Awaited<ReturnType<typeof getGenres>>;

export const getGenresSuspenseQueryKey = "getGenresSuspenseQueryKey";

export const getGenresSuspenseQueryOptions = <TData = GetGenresHookData, TError = DefaultError>(settings?: {
    params?: Omit<UseSuspenseQueryOptions<GetGenresHookData, TError, TData>, "queryKey">;
    request?: NonNullable<Parameters<typeof getGenres>[0]>;
}) => queryOptions({
    queryKey: [getGenresSuspenseQueryKey, ...(!!settings?.request?.path ? [settings?.request?.path] : []), ...(!!settings?.request?.query ? [settings?.request?.query] : []), ...(!!settings?.request?.body ? [settings?.request?.body] : [])],
    queryFn: async () => getGenres({ ...settings?.request }),
    ...settings?.params
});

export const useGetGenresSuspenseQuery = <TData = GetGenresHookData, TError = DefaultError>(...args: Parameters<typeof getGenresSuspenseQueryOptions<TData, TError>>) => useSuspenseQuery(getGenresSuspenseQueryOptions<TData, TError>(...args));