// This file is auto-generated by @hey-api/openapi-ts

import type { UseMutationOptions } from "@tanstack/react-query";

import { useMutation } from "@tanstack/react-query";

import type { GetAnimeByGenreGenresSlugAnimeGetError } from "..//..//types.gen";

import { getGenreBySlugAnime } from "..//..//requests//genres//getGenreBySlugAnime.gen";

type GetGenreBySlugAnimeHookData = Awaited<ReturnType<typeof getGenreBySlugAnime>>;

export const getGenreBySlugAnimeMutationKey = "getGenreBySlugAnimeMutationKey";

type GetGenreBySlugAnimeMutationVariables = Parameters<typeof getGenreBySlugAnime>[0];

export const useGetGenreBySlugAnimeMutation = <TError = GetAnimeByGenreGenresSlugAnimeGetError, TContext = unknown>(settings?: {
    params?: UseMutationOptions<GetGenreBySlugAnimeHookData, TError, GetGenreBySlugAnimeMutationVariables, TContext>;
    request?: NonNullable<GetGenreBySlugAnimeMutationVariables>;
}) => useMutation({
    mutationKey: [getGenreBySlugAnimeMutationKey],
    mutationFn: async (params) => getGenreBySlugAnime({ ...settings?.request, ...params }),
    ...settings?.params
});