// This file is auto-generated by @hey-api/openapi-ts

import type { UseSuspenseQueryOptions } from "@tanstack/react-query";

import { queryOptions, useSuspenseQuery } from "@tanstack/react-query";

import type { GetAnimeByGenreGenresSlugAnimeGetError } from "..//..//types.gen";

import { getGenreBySlugAnime } from "..//..//requests//genres//getGenreBySlugAnime.gen";

type GetGenreBySlugAnimeHookData = Awaited<ReturnType<typeof getGenreBySlugAnime>>;

export const getGenreBySlugAnimeSuspenseQueryKey = "getGenreBySlugAnimeSuspenseQueryKey";

export const getGenreBySlugAnimeSuspenseQueryOptions = <TData = GetGenreBySlugAnimeHookData, TError = GetAnimeByGenreGenresSlugAnimeGetError>(settings: {
    params?: Omit<UseSuspenseQueryOptions<GetGenreBySlugAnimeHookData, TError, TData>, "queryKey">;
    request: NonNullable<Parameters<typeof getGenreBySlugAnime>[0]>;
}) => queryOptions({
    queryKey: [getGenreBySlugAnimeSuspenseQueryKey, ...(!!settings.request.path ? [settings.request.path] : []), ...(!!settings.request.query ? [settings.request.query] : []), ...(!!settings.request.body ? [settings.request.body] : [])],
    queryFn: async () => getGenreBySlugAnime({ ...settings.request }),
    ...settings.params
});

export const useGetGenreBySlugAnimeSuspenseQuery = <TData = GetGenreBySlugAnimeHookData, TError = GetAnimeByGenreGenresSlugAnimeGetError>(...args: Parameters<typeof getGenreBySlugAnimeSuspenseQueryOptions<TData, TError>>) => useSuspenseQuery(getGenreBySlugAnimeSuspenseQueryOptions<TData, TError>(...args));