// This file is auto-generated by @hey-api/openapi-ts

import type { UseQueryOptions } from "@tanstack/react-query";

import { queryOptions, useQuery } from "@tanstack/react-query";

import type { GetAnimeByGenreGenresSlugAnimeGetError } from "..//..//types.gen";

import { getGenreBySlugAnime } from "..//..//requests//genres//getGenreBySlugAnime.gen";

type GetGenreBySlugAnimeHookData = Awaited<ReturnType<typeof getGenreBySlugAnime>>;

export const getGenreBySlugAnimeQueryKey = "getGenreBySlugAnimeQueryKey";

export const getGenreBySlugAnimeQueryOptions = <TData = GetGenreBySlugAnimeHookData, TError = GetAnimeByGenreGenresSlugAnimeGetError>(settings: {
    params?: Omit<UseQueryOptions<GetGenreBySlugAnimeHookData, TError, TData>, "queryKey">;
    request: NonNullable<Parameters<typeof getGenreBySlugAnime>[0]>;
}) => queryOptions({
    queryKey: [getGenreBySlugAnimeQueryKey, ...(!!settings.request.path ? [settings.request.path] : []), ...(!!settings.request.query ? [settings.request.query] : []), ...(!!settings.request.body ? [settings.request.body] : [])],
    queryFn: async () => getGenreBySlugAnime({ ...settings.request }),
    ...settings.params
});

export const useGetGenreBySlugAnimeQuery = <TData = GetGenreBySlugAnimeHookData, TError = GetAnimeByGenreGenresSlugAnimeGetError>(...args: Parameters<typeof getGenreBySlugAnimeQueryOptions<TData, TError>>) => useQuery(getGenreBySlugAnimeQueryOptions<TData, TError>(...args));