// This file is auto-generated by @hey-api/openapi-ts

import type { UseQueryOptions } from "@tanstack/react-query";

import { queryOptions, useQuery } from "@tanstack/react-query";

import type { GetTranslationTranslationGetError } from "..//..//types.gen";

import { getTranslation } from "..//..//requests//kodik//getTranslation.gen";

type GetTranslationHookData = Awaited<ReturnType<typeof getTranslation>>;

export const getTranslationQueryKey = "getTranslationQueryKey";

export const getTranslationQueryOptions = <TData = GetTranslationHookData, TError = GetTranslationTranslationGetError>(settings: {
    params?: Omit<UseQueryOptions<GetTranslationHookData, TError, TData>, "queryKey">;
    request: NonNullable<Parameters<typeof getTranslation>[0]>;
}) => queryOptions({
    queryKey: [getTranslationQueryKey, ...(!!settings.request.path ? [settings.request.path] : []), ...(!!settings.request.query ? [settings.request.query] : []), ...(!!settings.request.body ? [settings.request.body] : [])],
    queryFn: async () => getTranslation({ ...settings.request }),
    ...settings.params
});

export const useGetTranslationQuery = <TData = GetTranslationHookData, TError = GetTranslationTranslationGetError>(...args: Parameters<typeof getTranslationQueryOptions<TData, TError>>) => useQuery(getTranslationQueryOptions<TData, TError>(...args));