// This file is auto-generated by @hey-api/openapi-ts

import type { UseMutationOptions } from "@tanstack/react-query";

import { useMutation } from "@tanstack/react-query";

import type { GetTranslationTranslationGetError } from "..//..//types.gen";

import { getTranslation } from "..//..//requests//kodik//getTranslation.gen";

type GetTranslationHookData = Awaited<ReturnType<typeof getTranslation>>;

export const getTranslationMutationKey = "getTranslationMutationKey";

type GetTranslationMutationVariables = Parameters<typeof getTranslation>[0];

export const useGetTranslationMutation = <TError = GetTranslationTranslationGetError, TContext = unknown>(settings?: {
    params?: UseMutationOptions<GetTranslationHookData, TError, GetTranslationMutationVariables, TContext>;
    request?: NonNullable<GetTranslationMutationVariables>;
}) => useMutation({
    mutationKey: [getTranslationMutationKey],
    mutationFn: async (params) => getTranslation({ ...settings?.request, ...params }),
    ...settings?.params
});