// This file is auto-generated by @hey-api/openapi-ts

import type { UseQueryOptions } from "@tanstack/react-query";

import { queryOptions, useQuery } from "@tanstack/react-query";

import type { SearchAnimeShortSearchGetError } from "..//..//types.gen";

import { getShortSearch } from "..//..//requests//kodik//getShortSearch.gen";

type GetShortSearchHookData = Awaited<ReturnType<typeof getShortSearch>>;

export const getShortSearchQueryKey = "getShortSearchQueryKey";

export const getShortSearchQueryOptions = <TData = GetShortSearchHookData, TError = SearchAnimeShortSearchGetError>(settings: {
    params?: Omit<UseQueryOptions<GetShortSearchHookData, TError, TData>, "queryKey">;
    request: NonNullable<Parameters<typeof getShortSearch>[0]>;
}) => queryOptions({
    queryKey: [getShortSearchQueryKey, ...(!!settings.request.path ? [settings.request.path] : []), ...(!!settings.request.query ? [settings.request.query] : []), ...(!!settings.request.body ? [settings.request.body] : [])],
    queryFn: async () => getShortSearch({ ...settings.request }),
    ...settings.params
});

export const useGetShortSearchQuery = <TData = GetShortSearchHookData, TError = SearchAnimeShortSearchGetError>(...args: Parameters<typeof getShortSearchQueryOptions<TData, TError>>) => useQuery(getShortSearchQueryOptions<TData, TError>(...args));