// This file is auto-generated by @hey-api/openapi-ts

import type { UseSuspenseQueryOptions } from "@tanstack/react-query";

import { queryOptions, useSuspenseQuery } from "@tanstack/react-query";

import type { GetTranslationTranslationGetError } from "..//..//types.gen";

import { getTranslation } from "..//..//requests//kodik//getTranslation.gen";

type GetTranslationHookData = Awaited<ReturnType<typeof getTranslation>>;

export const getTranslationSuspenseQueryKey = "getTranslationSuspenseQueryKey";

export const getTranslationSuspenseQueryOptions = <TData = GetTranslationHookData, TError = GetTranslationTranslationGetError>(settings: {
    params?: Omit<UseSuspenseQueryOptions<GetTranslationHookData, TError, TData>, "queryKey">;
    request: NonNullable<Parameters<typeof getTranslation>[0]>;
}) => queryOptions({
    queryKey: [getTranslationSuspenseQueryKey, ...(!!settings.request.path ? [settings.request.path] : []), ...(!!settings.request.query ? [settings.request.query] : []), ...(!!settings.request.body ? [settings.request.body] : [])],
    queryFn: async () => getTranslation({ ...settings.request }),
    ...settings.params
});

export const useGetTranslationSuspenseQuery = <TData = GetTranslationHookData, TError = GetTranslationTranslationGetError>(...args: Parameters<typeof getTranslationSuspenseQueryOptions<TData, TError>>) => useSuspenseQuery(getTranslationSuspenseQueryOptions<TData, TError>(...args));