// This file is auto-generated by @hey-api/openapi-ts

import type { UseMutationOptions } from "@tanstack/react-query";

import { useMutation } from "@tanstack/react-query";

import type { SearchAnimeShortSearchGetError } from "..//..//types.gen";

import { getShortSearch } from "..//..//requests//kodik//getShortSearch.gen";

type GetShortSearchHookData = Awaited<ReturnType<typeof getShortSearch>>;

export const getShortSearchMutationKey = "getShortSearchMutationKey";

type GetShortSearchMutationVariables = Parameters<typeof getShortSearch>[0];

export const useGetShortSearchMutation = <TError = SearchAnimeShortSearchGetError, TContext = unknown>(settings?: {
    params?: UseMutationOptions<GetShortSearchHookData, TError, GetShortSearchMutationVariables, TContext>;
    request?: NonNullable<GetShortSearchMutationVariables>;
}) => useMutation({
    mutationKey: [getShortSearchMutationKey],
    mutationFn: async (params) => getShortSearch({ ...settings?.request, ...params }),
    ...settings?.params
});