// This file is auto-generated by @hey-api/openapi-ts

import type { UseSuspenseQueryOptions } from "@tanstack/react-query";

import { queryOptions, useSuspenseQuery } from "@tanstack/react-query";

import type { SearchAnimeShortSearchGetError } from "..//..//types.gen";

import { getShortSearch } from "..//..//requests//kodik//getShortSearch.gen";

type GetShortSearchHookData = Awaited<ReturnType<typeof getShortSearch>>;

export const getShortSearchSuspenseQueryKey = "getShortSearchSuspenseQueryKey";

export const getShortSearchSuspenseQueryOptions = <TData = GetShortSearchHookData, TError = SearchAnimeShortSearchGetError>(settings: {
    params?: Omit<UseSuspenseQueryOptions<GetShortSearchHookData, TError, TData>, "queryKey">;
    request: NonNullable<Parameters<typeof getShortSearch>[0]>;
}) => queryOptions({
    queryKey: [getShortSearchSuspenseQueryKey, ...(!!settings.request.path ? [settings.request.path] : []), ...(!!settings.request.query ? [settings.request.query] : []), ...(!!settings.request.body ? [settings.request.body] : [])],
    queryFn: async () => getShortSearch({ ...settings.request }),
    ...settings.params
});

export const useGetShortSearchSuspenseQuery = <TData = GetShortSearchHookData, TError = SearchAnimeShortSearchGetError>(...args: Parameters<typeof getShortSearchSuspenseQueryOptions<TData, TError>>) => useSuspenseQuery(getShortSearchSuspenseQueryOptions<TData, TError>(...args));