// This file is auto-generated by @hey-api/openapi-ts

import type { UseQueryOptions, DefaultError } from "@tanstack/react-query";

import { queryOptions, useQuery } from "@tanstack/react-query";

import { getPopulars } from "..//..//requests//popular//getPopulars.gen";

type GetPopularsHookData = Awaited<ReturnType<typeof getPopulars>>;

export const getPopularsQueryKey = "getPopularsQueryKey";

export const getPopularsQueryOptions = <TData = GetPopularsHookData, TError = DefaultError>(settings?: {
    params?: Omit<UseQueryOptions<GetPopularsHookData, TError, TData>, "queryKey">;
    request?: NonNullable<Parameters<typeof getPopulars>[0]>;
}) => queryOptions({
    queryKey: [getPopularsQueryKey, ...(!!settings?.request?.path ? [settings?.request?.path] : []), ...(!!settings?.request?.query ? [settings?.request?.query] : []), ...(!!settings?.request?.body ? [settings?.request?.body] : [])],
    queryFn: async () => getPopulars({ ...settings?.request }),
    ...settings?.params
});

export const useGetPopularsQuery = <TData = GetPopularsHookData, TError = DefaultError>(...args: Parameters<typeof getPopularsQueryOptions<TData, TError>>) => useQuery(getPopularsQueryOptions<TData, TError>(...args));