// This file is auto-generated by @hey-api/openapi-ts

import type { UseSuspenseQueryOptions, DefaultError } from "@tanstack/react-query";

import { queryOptions, useSuspenseQuery } from "@tanstack/react-query";

import { getPopulars } from "..//..//requests//popular//getPopulars.gen";

type GetPopularsHookData = Awaited<ReturnType<typeof getPopulars>>;

export const getPopularsSuspenseQueryKey = "getPopularsSuspenseQueryKey";

export const getPopularsSuspenseQueryOptions = <TData = GetPopularsHookData, TError = DefaultError>(settings?: {
    params?: Omit<UseSuspenseQueryOptions<GetPopularsHookData, TError, TData>, "queryKey">;
    request?: NonNullable<Parameters<typeof getPopulars>[0]>;
}) => queryOptions({
    queryKey: [getPopularsSuspenseQueryKey, ...(!!settings?.request?.path ? [settings?.request?.path] : []), ...(!!settings?.request?.query ? [settings?.request?.query] : []), ...(!!settings?.request?.body ? [settings?.request?.body] : [])],
    queryFn: async () => getPopulars({ ...settings?.request }),
    ...settings?.params
});

export const useGetPopularsSuspenseQuery = <TData = GetPopularsHookData, TError = DefaultError>(...args: Parameters<typeof getPopularsSuspenseQueryOptions<TData, TError>>) => useSuspenseQuery(getPopularsSuspenseQueryOptions<TData, TError>(...args));