// This file is auto-generated by @hey-api/openapi-ts

import type { UseMutationOptions, DefaultError } from "@tanstack/react-query";

import { useMutation } from "@tanstack/react-query";

import { getPopulars } from "..//..//requests//popular//getPopulars.gen";

type GetPopularsHookData = Awaited<ReturnType<typeof getPopulars>>;

export const getPopularsMutationKey = "getPopularsMutationKey";

type GetPopularsMutationVariables = Parameters<typeof getPopulars>[0];

export const useGetPopularsMutation = <TError = DefaultError, TContext = unknown>(settings?: {
    params?: UseMutationOptions<GetPopularsHookData, TError, GetPopularsMutationVariables, TContext>;
    request?: NonNullable<GetPopularsMutationVariables>;
}) => useMutation({
    mutationKey: [getPopularsMutationKey],
    mutationFn: async (params) => getPopulars({ ...settings?.request, ...params }),
    ...settings?.params
});