// This file is auto-generated by @hey-api/openapi-ts

import type { FetchesRequestParams, ApicraftFetchesResponse } from '@siberiacancode/apicraft';

import type {
  GetAnimeTitleGetData,
  GetAnimeTitleGetResponse,
  GetAnimeTitleGetError
} from '..//..//types.gen';

import { instance } from '../../instance.gen';

export type GetTitleRequestParams = FetchesRequestParams<GetAnimeTitleGetData>;

export const getTitle = ({
  config,
  query
}: GetTitleRequestParams): Promise<
  ApicraftFetchesResponse<GetAnimeTitleGetResponse, GetAnimeTitleGetError>
> =>
  instance.call('GET', '/title', {
    query,
    ...config
  });
