// This file is auto-generated by @hey-api/openapi-ts

import type { FetchesRequestParams, ApicraftFetchesResponse } from '@siberiacancode/apicraft';

import type {
  GetPlayerTitlePlayerGetData,
  GetPlayerTitlePlayerGetResponse,
  GetPlayerTitlePlayerGetError
} from '..//..//types.gen';

import { instance } from '../../instance.gen';

export type GetTitlePlayerRequestParams = FetchesRequestParams<GetPlayerTitlePlayerGetData>;

export const getTitlePlayer = ({
  config,
  query
}: GetTitlePlayerRequestParams): Promise<
  ApicraftFetchesResponse<GetPlayerTitlePlayerGetResponse, GetPlayerTitlePlayerGetError>
> =>
  instance.call('GET', '/title/player', {
    query,
    ...config
  });
