// This file is auto-generated by @hey-api/openapi-ts

import type { UseQueryOptions } from "@tanstack/react-query";

import { queryOptions, useQuery } from "@tanstack/react-query";

import type { GetProfileProfileUsernameGetError } from "..//..//types.gen";

import { getProfileByUsername } from "..//..//requests//profile//getProfileByUsername.gen";

type GetProfileByUsernameHookData = Awaited<ReturnType<typeof getProfileByUsername>>;

export const getProfileByUsernameQueryKey = "getProfileByUsernameQueryKey";

export const getProfileByUsernameQueryOptions = <TData = GetProfileByUsernameHookData, TError = GetProfileProfileUsernameGetError>(settings: {
    params?: Omit<UseQueryOptions<GetProfileByUsernameHookData, TError, TData>, "queryKey">;
    request: NonNullable<Parameters<typeof getProfileByUsername>[0]>;
}) => queryOptions({
    queryKey: [getProfileByUsernameQueryKey, ...(!!settings.request.path ? [settings.request.path] : []), ...(!!settings.request.query ? [settings.request.query] : []), ...(!!settings.request.body ? [settings.request.body] : [])],
    queryFn: async () => getProfileByUsername({ ...settings.request }),
    ...settings.params
});

export const useGetProfileByUsernameQuery = <TData = GetProfileByUsernameHookData, TError = GetProfileProfileUsernameGetError>(...args: Parameters<typeof getProfileByUsernameQueryOptions<TData, TError>>) => useQuery(getProfileByUsernameQueryOptions<TData, TError>(...args));