// This file is auto-generated by @hey-api/openapi-ts

import type { UseSuspenseQueryOptions } from "@tanstack/react-query";

import { queryOptions, useSuspenseQuery } from "@tanstack/react-query";

import type { GetProfileImageProfileImagesPathnameGetError } from "..//..//types.gen";

import { getProfileImageByPathname } from "..//..//requests//profile//getProfileImageByPathname.gen";

type GetProfileImageByPathnameHookData = Awaited<ReturnType<typeof getProfileImageByPathname>>;

export const getProfileImageByPathnameSuspenseQueryKey = "getProfileImageByPathnameSuspenseQueryKey";

export const getProfileImageByPathnameSuspenseQueryOptions = <TData = GetProfileImageByPathnameHookData, TError = GetProfileImageProfileImagesPathnameGetError>(settings: {
    params?: Omit<UseSuspenseQueryOptions<GetProfileImageByPathnameHookData, TError, TData>, "queryKey">;
    request: NonNullable<Parameters<typeof getProfileImageByPathname>[0]>;
}) => queryOptions({
    queryKey: [getProfileImageByPathnameSuspenseQueryKey, ...(!!settings.request.path ? [settings.request.path] : []), ...(!!settings.request.query ? [settings.request.query] : []), ...(!!settings.request.body ? [settings.request.body] : [])],
    queryFn: async () => getProfileImageByPathname({ ...settings.request }),
    ...settings.params
});

export const useGetProfileImageByPathnameSuspenseQuery = <TData = GetProfileImageByPathnameHookData, TError = GetProfileImageProfileImagesPathnameGetError>(...args: Parameters<typeof getProfileImageByPathnameSuspenseQueryOptions<TData, TError>>) => useSuspenseQuery(getProfileImageByPathnameSuspenseQueryOptions<TData, TError>(...args));