// This file is auto-generated by @hey-api/openapi-ts

import type { UseMutationOptions } from "@tanstack/react-query";

import { useMutation } from "@tanstack/react-query";

import type { GetProfileProfileUsernameGetError } from "..//..//types.gen";

import { getProfileByUsername } from "..//..//requests//profile//getProfileByUsername.gen";

type GetProfileByUsernameHookData = Awaited<ReturnType<typeof getProfileByUsername>>;

export const getProfileByUsernameMutationKey = "getProfileByUsernameMutationKey";

type GetProfileByUsernameMutationVariables = Parameters<typeof getProfileByUsername>[0];

export const useGetProfileByUsernameMutation = <TError = GetProfileProfileUsernameGetError, TContext = unknown>(settings?: {
    params?: UseMutationOptions<GetProfileByUsernameHookData, TError, GetProfileByUsernameMutationVariables, TContext>;
    request?: NonNullable<GetProfileByUsernameMutationVariables>;
}) => useMutation({
    mutationKey: [getProfileByUsernameMutationKey],
    mutationFn: async (params) => getProfileByUsername({ ...settings?.request, ...params }),
    ...settings?.params
});