// This file is auto-generated by @hey-api/openapi-ts

import type { UseMutationOptions } from "@tanstack/react-query";

import { useMutation } from "@tanstack/react-query";

import type { GetProfileImageProfileImagesPathnameGetError } from "..//..//types.gen";

import { getProfileImageByPathname } from "..//..//requests//profile//getProfileImageByPathname.gen";

type GetProfileImageByPathnameHookData = Awaited<ReturnType<typeof getProfileImageByPathname>>;

export const getProfileImageByPathnameMutationKey = "getProfileImageByPathnameMutationKey";

type GetProfileImageByPathnameMutationVariables = Parameters<typeof getProfileImageByPathname>[0];

export const useGetProfileImageByPathnameMutation = <TError = GetProfileImageProfileImagesPathnameGetError, TContext = unknown>(settings?: {
    params?: UseMutationOptions<GetProfileImageByPathnameHookData, TError, GetProfileImageByPathnameMutationVariables, TContext>;
    request?: NonNullable<GetProfileImageByPathnameMutationVariables>;
}) => useMutation({
    mutationKey: [getProfileImageByPathnameMutationKey],
    mutationFn: async (params) => getProfileImageByPathname({ ...settings?.request, ...params }),
    ...settings?.params
});