// This file is auto-generated by @hey-api/openapi-ts

import type { UseSuspenseQueryOptions } from "@tanstack/react-query";

import { queryOptions, useSuspenseQuery } from "@tanstack/react-query";

import type { GetProfileProfileUsernameGetError } from "..//..//types.gen";

import { getProfileByUsername } from "..//..//requests//profile//getProfileByUsername.gen";

type GetProfileByUsernameHookData = Awaited<ReturnType<typeof getProfileByUsername>>;

export const getProfileByUsernameSuspenseQueryKey = "getProfileByUsernameSuspenseQueryKey";

export const getProfileByUsernameSuspenseQueryOptions = <TData = GetProfileByUsernameHookData, TError = GetProfileProfileUsernameGetError>(settings: {
    params?: Omit<UseSuspenseQueryOptions<GetProfileByUsernameHookData, TError, TData>, "queryKey">;
    request: NonNullable<Parameters<typeof getProfileByUsername>[0]>;
}) => queryOptions({
    queryKey: [getProfileByUsernameSuspenseQueryKey, ...(!!settings.request.path ? [settings.request.path] : []), ...(!!settings.request.query ? [settings.request.query] : []), ...(!!settings.request.body ? [settings.request.body] : [])],
    queryFn: async () => getProfileByUsername({ ...settings.request }),
    ...settings.params
});

export const useGetProfileByUsernameSuspenseQuery = <TData = GetProfileByUsernameHookData, TError = GetProfileProfileUsernameGetError>(...args: Parameters<typeof getProfileByUsernameSuspenseQueryOptions<TData, TError>>) => useSuspenseQuery(getProfileByUsernameSuspenseQueryOptions<TData, TError>(...args));