// This file is auto-generated by @hey-api/openapi-ts

import type { UseQueryOptions } from "@tanstack/react-query";

import { queryOptions, useQuery } from "@tanstack/react-query";

import type { GetProfileImageProfileImagesPathnameGetError } from "..//..//types.gen";

import { getProfileImageByPathname } from "..//..//requests//profile//getProfileImageByPathname.gen";

type GetProfileImageByPathnameHookData = Awaited<ReturnType<typeof getProfileImageByPathname>>;

export const getProfileImageByPathnameQueryKey = "getProfileImageByPathnameQueryKey";

export const getProfileImageByPathnameQueryOptions = <TData = GetProfileImageByPathnameHookData, TError = GetProfileImageProfileImagesPathnameGetError>(settings: {
    params?: Omit<UseQueryOptions<GetProfileImageByPathnameHookData, TError, TData>, "queryKey">;
    request: NonNullable<Parameters<typeof getProfileImageByPathname>[0]>;
}) => queryOptions({
    queryKey: [getProfileImageByPathnameQueryKey, ...(!!settings.request.path ? [settings.request.path] : []), ...(!!settings.request.query ? [settings.request.query] : []), ...(!!settings.request.body ? [settings.request.body] : [])],
    queryFn: async () => getProfileImageByPathname({ ...settings.request }),
    ...settings.params
});

export const useGetProfileImageByPathnameQuery = <TData = GetProfileImageByPathnameHookData, TError = GetProfileImageProfileImagesPathnameGetError>(...args: Parameters<typeof getProfileImageByPathnameQueryOptions<TData, TError>>) => useQuery(getProfileImageByPathnameQueryOptions<TData, TError>(...args));