// This file is auto-generated by @hey-api/openapi-ts

import type { UseQueryOptions } from "@tanstack/react-query";

import { queryOptions, useQuery } from "@tanstack/react-query";

import type { UpdateProfileProfileMePatchError } from "..//..//types.gen";

import { patchProfileMe } from "..//..//requests//profile//patchProfileMe.gen";

type PatchProfileMeHookData = Awaited<ReturnType<typeof patchProfileMe>>;

export const patchProfileMeQueryKey = "patchProfileMeQueryKey";

export const patchProfileMeQueryOptions = <TData = PatchProfileMeHookData, TError = UpdateProfileProfileMePatchError>(settings: {
    params?: Omit<UseQueryOptions<PatchProfileMeHookData, TError, TData>, "queryKey">;
    request: NonNullable<Parameters<typeof patchProfileMe>[0]>;
}) => queryOptions({
    queryKey: [patchProfileMeQueryKey, ...(!!settings.request.path ? [settings.request.path] : []), ...(!!settings.request.query ? [settings.request.query] : []), ...(!!settings.request.body ? [settings.request.body] : [])],
    queryFn: async () => patchProfileMe({ ...settings.request }),
    ...settings.params
});

export const usePatchProfileMeQuery = <TData = PatchProfileMeHookData, TError = UpdateProfileProfileMePatchError>(...args: Parameters<typeof patchProfileMeQueryOptions<TData, TError>>) => useQuery(patchProfileMeQueryOptions<TData, TError>(...args));