// This file is auto-generated by @hey-api/openapi-ts

import type { UseMutationOptions } from "@tanstack/react-query";

import { useMutation } from "@tanstack/react-query";

import type { UploadProfileImageProfileMeImageTypePostError } from "..//..//types.gen";

import { postProfileMeByImageType } from "..//..//requests//profile//postProfileMeByImageType.gen";

type PostProfileMeByImageTypeHookData = Awaited<ReturnType<typeof postProfileMeByImageType>>;

export const postProfileMeByImageTypeMutationKey = "postProfileMeByImageTypeMutationKey";

type PostProfileMeByImageTypeMutationVariables = Parameters<typeof postProfileMeByImageType>[0];

export const usePostProfileMeByImageTypeMutation = <TError = UploadProfileImageProfileMeImageTypePostError, TContext = unknown>(settings?: {
    params?: UseMutationOptions<PostProfileMeByImageTypeHookData, TError, PostProfileMeByImageTypeMutationVariables, TContext>;
    request?: NonNullable<PostProfileMeByImageTypeMutationVariables>;
}) => useMutation({
    mutationKey: [postProfileMeByImageTypeMutationKey],
    mutationFn: async (params) => postProfileMeByImageType({ ...settings?.request, ...params }),
    ...settings?.params
});