// This file is auto-generated by @hey-api/openapi-ts

import type { UseSuspenseQueryOptions } from "@tanstack/react-query";

import { queryOptions, useSuspenseQuery } from "@tanstack/react-query";

import type { UploadProfileImageProfileMeImageTypePostError } from "..//..//types.gen";

import { postProfileMeByImageType } from "..//..//requests//profile//postProfileMeByImageType.gen";

type PostProfileMeByImageTypeHookData = Awaited<ReturnType<typeof postProfileMeByImageType>>;

export const postProfileMeByImageTypeSuspenseQueryKey = "postProfileMeByImageTypeSuspenseQueryKey";

export const postProfileMeByImageTypeSuspenseQueryOptions = <TData = PostProfileMeByImageTypeHookData, TError = UploadProfileImageProfileMeImageTypePostError>(settings: {
    params?: Omit<UseSuspenseQueryOptions<PostProfileMeByImageTypeHookData, TError, TData>, "queryKey">;
    request: NonNullable<Parameters<typeof postProfileMeByImageType>[0]>;
}) => queryOptions({
    queryKey: [postProfileMeByImageTypeSuspenseQueryKey, ...(!!settings.request.path ? [settings.request.path] : []), ...(!!settings.request.query ? [settings.request.query] : []), ...(!!settings.request.body ? [settings.request.body] : [])],
    queryFn: async () => postProfileMeByImageType({ ...settings.request }),
    ...settings.params
});

export const usePostProfileMeByImageTypeSuspenseQuery = <TData = PostProfileMeByImageTypeHookData, TError = UploadProfileImageProfileMeImageTypePostError>(...args: Parameters<typeof postProfileMeByImageTypeSuspenseQueryOptions<TData, TError>>) => useSuspenseQuery(postProfileMeByImageTypeSuspenseQueryOptions<TData, TError>(...args));