// This file is auto-generated by @hey-api/openapi-ts

import type { UseMutationOptions } from "@tanstack/react-query";

import { useMutation } from "@tanstack/react-query";

import type { UpdateProfileProfileMePatchError } from "..//..//types.gen";

import { patchProfileMe } from "..//..//requests//profile//patchProfileMe.gen";

type PatchProfileMeHookData = Awaited<ReturnType<typeof patchProfileMe>>;

export const patchProfileMeMutationKey = "patchProfileMeMutationKey";

type PatchProfileMeMutationVariables = Parameters<typeof patchProfileMe>[0];

export const usePatchProfileMeMutation = <TError = UpdateProfileProfileMePatchError, TContext = unknown>(settings?: {
    params?: UseMutationOptions<PatchProfileMeHookData, TError, PatchProfileMeMutationVariables, TContext>;
    request?: NonNullable<PatchProfileMeMutationVariables>;
}) => useMutation({
    mutationKey: [patchProfileMeMutationKey],
    mutationFn: async (params) => patchProfileMe({ ...settings?.request, ...params }),
    ...settings?.params
});