// This file is auto-generated by @hey-api/openapi-ts

import type { UseQueryOptions } from "@tanstack/react-query";

import { queryOptions, useQuery } from "@tanstack/react-query";

import type { UploadProfileImageProfileMeImageTypePostError } from "..//..//types.gen";

import { postProfileMeByImageType } from "..//..//requests//profile//postProfileMeByImageType.gen";

type PostProfileMeByImageTypeHookData = Awaited<ReturnType<typeof postProfileMeByImageType>>;

export const postProfileMeByImageTypeQueryKey = "postProfileMeByImageTypeQueryKey";

export const postProfileMeByImageTypeQueryOptions = <TData = PostProfileMeByImageTypeHookData, TError = UploadProfileImageProfileMeImageTypePostError>(settings: {
    params?: Omit<UseQueryOptions<PostProfileMeByImageTypeHookData, TError, TData>, "queryKey">;
    request: NonNullable<Parameters<typeof postProfileMeByImageType>[0]>;
}) => queryOptions({
    queryKey: [postProfileMeByImageTypeQueryKey, ...(!!settings.request.path ? [settings.request.path] : []), ...(!!settings.request.query ? [settings.request.query] : []), ...(!!settings.request.body ? [settings.request.body] : [])],
    queryFn: async () => postProfileMeByImageType({ ...settings.request }),
    ...settings.params
});

export const usePostProfileMeByImageTypeQuery = <TData = PostProfileMeByImageTypeHookData, TError = UploadProfileImageProfileMeImageTypePostError>(...args: Parameters<typeof postProfileMeByImageTypeQueryOptions<TData, TError>>) => useQuery(postProfileMeByImageTypeQueryOptions<TData, TError>(...args));