// This file is auto-generated by @hey-api/openapi-ts

import type { UseSuspenseQueryOptions } from "@tanstack/react-query";

import { queryOptions, useSuspenseQuery } from "@tanstack/react-query";

import type { UpdateProfileProfileMePatchError } from "..//..//types.gen";

import { patchProfileMe } from "..//..//requests//profile//patchProfileMe.gen";

type PatchProfileMeHookData = Awaited<ReturnType<typeof patchProfileMe>>;

export const patchProfileMeSuspenseQueryKey = "patchProfileMeSuspenseQueryKey";

export const patchProfileMeSuspenseQueryOptions = <TData = PatchProfileMeHookData, TError = UpdateProfileProfileMePatchError>(settings: {
    params?: Omit<UseSuspenseQueryOptions<PatchProfileMeHookData, TError, TData>, "queryKey">;
    request: NonNullable<Parameters<typeof patchProfileMe>[0]>;
}) => queryOptions({
    queryKey: [patchProfileMeSuspenseQueryKey, ...(!!settings.request.path ? [settings.request.path] : []), ...(!!settings.request.query ? [settings.request.query] : []), ...(!!settings.request.body ? [settings.request.body] : [])],
    queryFn: async () => patchProfileMe({ ...settings.request }),
    ...settings.params
});

export const usePatchProfileMeSuspenseQuery = <TData = PatchProfileMeHookData, TError = UpdateProfileProfileMePatchError>(...args: Parameters<typeof patchProfileMeSuspenseQueryOptions<TData, TError>>) => useSuspenseQuery(patchProfileMeSuspenseQueryOptions<TData, TError>(...args));