// This file is auto-generated by @hey-api/openapi-ts

import type { UseQueryOptions, DefaultError } from "@tanstack/react-query";

import { queryOptions, useQuery } from "@tanstack/react-query";

import { get } from "..//..//requests//default//get.gen";

type GetHookData = Awaited<ReturnType<typeof get>>;

export const getQueryKey = "getQueryKey";

export const getQueryOptions = <TData = GetHookData, TError = DefaultError>(settings?: {
    params?: Omit<UseQueryOptions<GetHookData, TError, TData>, "queryKey">;
    request?: NonNullable<Parameters<typeof get>[0]>;
}) => queryOptions({
    queryKey: [getQueryKey, ...(!!settings?.request?.path ? [settings?.request?.path] : []), ...(!!settings?.request?.query ? [settings?.request?.query] : []), ...(!!settings?.request?.body ? [settings?.request?.body] : [])],
    queryFn: async () => get({ ...settings?.request }),
    ...settings?.params
});

export const useGetQuery = <TData = GetHookData, TError = DefaultError>(...args: Parameters<typeof getQueryOptions<TData, TError>>) => useQuery(getQueryOptions<TData, TError>(...args));