// This file is auto-generated by @hey-api/openapi-ts

import type { UseMutationOptions, DefaultError } from "@tanstack/react-query";

import { useMutation } from "@tanstack/react-query";

import { get } from "..//..//requests//default//get.gen";

type GetHookData = Awaited<ReturnType<typeof get>>;

export const getMutationKey = "getMutationKey";

type GetMutationVariables = Parameters<typeof get>[0];

export const useGetMutation = <TError = DefaultError, TContext = unknown>(settings?: {
    params?: UseMutationOptions<GetHookData, TError, GetMutationVariables, TContext>;
    request?: NonNullable<GetMutationVariables>;
}) => useMutation({
    mutationKey: [getMutationKey],
    mutationFn: async (params) => get({ ...settings?.request, ...params }),
    ...settings?.params
});