// This file is auto-generated by @hey-api/openapi-ts

import type { UseSuspenseQueryOptions, DefaultError } from "@tanstack/react-query";

import { queryOptions, useSuspenseQuery } from "@tanstack/react-query";

import { get } from "..//..//requests//default//get.gen";

type GetHookData = Awaited<ReturnType<typeof get>>;

export const getSuspenseQueryKey = "getSuspenseQueryKey";

export const getSuspenseQueryOptions = <TData = GetHookData, TError = DefaultError>(settings?: {
    params?: Omit<UseSuspenseQueryOptions<GetHookData, TError, TData>, "queryKey">;
    request?: NonNullable<Parameters<typeof get>[0]>;
}) => queryOptions({
    queryKey: [getSuspenseQueryKey, ...(!!settings?.request?.path ? [settings?.request?.path] : []), ...(!!settings?.request?.query ? [settings?.request?.query] : []), ...(!!settings?.request?.body ? [settings?.request?.body] : [])],
    queryFn: async () => get({ ...settings?.request }),
    ...settings?.params
});

export const useGetSuspenseQuery = <TData = GetHookData, TError = DefaultError>(...args: Parameters<typeof getSuspenseQueryOptions<TData, TError>>) => useSuspenseQuery(getSuspenseQueryOptions<TData, TError>(...args));